# Generated by Django 5.2 on 2026-08-29 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_users", "0002_competencecandidat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "typeMission",
                    models.CharField(
                        choices=[
                            ("ponctuelle", "Mission ponctuelle"),
                            ("projet", "Projet"),
                            ("longue_duree", "Longue durée"),
                            ("temps_partiel", "Temps partiel"),
                            ("temps_plein", "Temps plein"),
                        ],
                        default="projet",
                        max_length=50,
                    ),
                ),
                ("domaine", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "modeTravail",
                    models.CharField(
                        choices=[
                            ("sur_place", "Sur place"),
                            ("hybride", "Hybride"),
                            ("distance", "À distance"),
                        ],
                        default="distance",
                        max_length=30,
                    ),
                ),
                (
                    "budgetMin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budgetMax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("deviseBudget", models.CharField(default="FCFA", max_length=10)),
                ("datePublication", models.DateTimeField(auto_now_add=True)),
                ("dateLimite", models.DateField(blank=True, null=True)),
                ("dateDebut", models.DateField(blank=True, null=True)),
                ("dateFinPrevue", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publiee", "Publiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                            ("fermee", "Fermée"),
                        ],
                        default="brouillon",
                        max_length=30,
                    ),
                ),
                ("nombreCandidats", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="app_users.entreprise",
                    ),
                ),
                (
                    "freelance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to="app_users.profil",
                    ),
                ),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions_publiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetenceMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "niveauRequis",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="intermediaire",
                        max_length=30,
                    ),
                ),
                ("estObligatoire", models.BooleanField(default=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competences",
                        to="app_missions.mission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mission", "nom"), name="unique_competence_mission"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CandidatureMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposition", models.TextField(blank=True, null=True)),
                (
                    "montantPropose",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("devise", models.CharField(default="FCFA", max_length=10)),
                (
                    "delaiPropose",
                    models.PositiveIntegerField(
                        blank=True, help_text="Durée proposée en jours", null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyee", "Envoyée"),
                            ("en_examen", "En examen"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("retiree", "Retirée"),
                        ],
                        default="envoyee",
                        max_length=30,
                    ),
                ),
                ("dateCandidature", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "freelance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures_missions",
                        to="app_users.profil",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="app_missions.mission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mission", "freelance"),
                        name="unique_candidature_mission_freelance",
                    )
                ],
            },
        ),
    ]
