# Generated by Django 6.0.6 on 2026-06-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSoumission', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='En attente', max_length=50)),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('candidat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('offre_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
