# Generated by Django 6.0.6 on 2026-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettreMotivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres/'),
        ),
    ]
