# Generated by Django 6.0.7 on 2026-07-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competances', '0002_alter_competence_id_alter_niveaucompetenceoffre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='niveaucompetenceoffre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
