# Generated by Django 5.2 on 2026-08-12 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NiveauCompetenceOffre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveauRequis",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("estObligatoire", models.BooleanField(default=True)),
                (
                    "competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux_offres",
                        to="offres.competence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "typeOffre",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("stage", "Stage"),
                            ("freelance", "Freelance"),
                            ("alternance", "Alternance"),
                            ("interim", "Intérim"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "salaireMin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salaireMax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("deviseSalaire", models.CharField(default="FCFA", max_length=10)),
                ("datePublication", models.DateTimeField(auto_now_add=True)),
                ("dateLimite", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente", "En attente"),
                            ("publiee", "Publiée"),
                            ("suspendue", "Suspendue"),
                            ("expiree", "Expirée"),
                            ("fermee", "Fermée"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competences",
                    models.ManyToManyField(
                        related_name="offres",
                        through="offres.NiveauCompetenceOffre",
                        to="offres.competence",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offres",
                        to="app_users.entreprise",
                    ),
                ),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offres_publiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="niveaucompetenceoffre",
            name="offre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveaux_competences",
                to="offres.offre",
            ),
        ),
        migrations.AddConstraint(
            model_name="niveaucompetenceoffre",
            constraint=models.UniqueConstraint(
                fields=("offre", "competence"), name="unique_competence_offre"
            ),
        ),
    ]
