# Generated by Django 5.2 on 2026-08-12 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateSoumission", models.DateTimeField(auto_now_add=True)),
                ("dateModification", models.DateTimeField(auto_now=True)),
                ("nombre_modifications", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Présélectionnée", "Présélectionnée"),
                            ("Entretien", "Entretien"),
                            ("Acceptée", "Acceptée"),
                            ("Refusée", "Refusée"),
                            ("Retirée", "Retirée"),
                        ],
                        default="En attente",
                        max_length=50,
                    ),
                ),
                ("lettreMotivation", models.TextField(blank=True, null=True)),
                ("commentaireRecruteur", models.TextField(blank=True, null=True)),
                ("dateDecision", models.DateTimeField(blank=True, null=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="offres.offre",
                    ),
                ),
            ],
            options={
                "ordering": ["-dateSoumission"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomFichier", models.CharField(max_length=200)),
                (
                    "typeFichier",
                    models.CharField(
                        choices=[
                            ("CV", "CV"),
                            ("Lettre", "Lettre de motivation"),
                            ("Diplome", "Diplôme"),
                            ("Certificat", "Certificat"),
                            ("Portfolio", "Portfolio"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=50,
                    ),
                ),
                ("contenu", models.FileField(upload_to="candidatures/%Y/%m/%d/")),
                ("taille", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app_candidatures.candidature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entretien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateHeure", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Visio", "Visio"),
                            ("Présentiel", "Présentiel"),
                            ("Téléphonique", "Téléphonique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("lieu", models.CharField(blank=True, max_length=255, null=True)),
                ("lienVisio", models.URLField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Planifié", "Planifié"),
                            ("Confirmé", "Confirmé"),
                            ("Terminé", "Terminé"),
                            ("Annulé", "Annulé"),
                            ("Reporté", "Reporté"),
                        ],
                        default="Planifié",
                        max_length=50,
                    ),
                ),
                (
                    "reponseCandidat",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Confirmé", "Confirmé"),
                            ("Refusé", "Refusé"),
                        ],
                        default="En attente",
                        max_length=50,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("motifAnnulation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entretiens",
                        to="app_candidatures.candidature",
                    ),
                ),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entretiens_animes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["dateHeure"],
            },
        ),
        migrations.AddConstraint(
            model_name="candidature",
            constraint=models.UniqueConstraint(
                fields=("candidat", "offre"), name="unique_candidature_par_offre"
            ),
        ),
    ]
