# Generated by Django 6.0.7 on 2026-07-24 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_candidatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeure', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('statut', models.CharField(default='Planifié', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_candidatures.candidature')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens_animes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
