# Generated by Django 5.2.15 on 2026-06-30 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numCni", models.CharField(blank=True, max_length=50, null=True)),
                ("dateNaissance", models.DateField(blank=True, null=True)),
                (
                    "lieuNaissance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("numPassport", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("candidat", "Candidat"),
                            ("recruteur", "Recruteur"),
                            ("admin", "Administrateur"),
                        ],
                        default="candidat",
                        max_length=20,
                    ),
                ),
                (
                    "niveauEtude",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dernierDiplome",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dateObtentionDiplome", models.DateField(blank=True, null=True)),
                ("nationalite", models.CharField(blank=True, max_length=50, null=True)),
                ("specialite", models.CharField(blank=True, max_length=100, null=True)),
                ("statut", models.CharField(blank=True, max_length=50, null=True)),
                ("dateEmbauche", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
