# Generated by Django 5.2 on 2026-08-12 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("secteur", models.CharField(blank=True, max_length=100, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("siteweb", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="entreprises/logos/"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("active", "Active"),
                            ("suspendue", "Suspendue"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("verifiee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("dateEnvoi", models.DateTimeField(auto_now_add=True)),
                ("lu", models.BooleanField(default=False)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_envoyes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("dateEnvoi", models.DateTimeField(auto_now_add=True)),
                ("lu", models.BooleanField(default=False)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("candidat", "Candidat"),
                            ("recruteur", "Recruteur"),
                            ("freelance", "Freelance"),
                        ],
                        default="candidat",
                        max_length=20,
                    ),
                ),
                (
                    "numCni",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("dateNaissance", models.DateField(blank=True, null=True)),
                (
                    "lieuNaissance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                (
                    "numPassport",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("nationalite", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "niveauEtude",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dernierDiplome",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dateObtentionDiplome", models.DateField(blank=True, null=True)),
                ("specialite", models.CharField(blank=True, max_length=150, null=True)),
                ("dateEmbauche", models.DateField(blank=True, null=True)),
                ("fonction", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "statut_recruteur",
                    models.CharField(
                        choices=[
                            ("non_concerne", "Non concerné"),
                            ("en_attente", "En attente"),
                            ("verifie", "Vérifié"),
                            ("refuse", "Refusé"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="non_concerne",
                        max_length=20,
                    ),
                ),
                (
                    "titreProfessionnel",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("biographie", models.TextField(blank=True, null=True)),
                ("anneesExperience", models.PositiveIntegerField(default=0)),
                (
                    "tarifHoraire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("deviseTarif", models.CharField(default="FCFA", max_length=10)),
                ("disponibilite", models.BooleanField(default=True)),
                ("portfolioUrl", models.URLField(blank=True, null=True)),
                ("linkedinUrl", models.URLField(blank=True, null=True)),
                ("githubUrl", models.URLField(blank=True, null=True)),
                (
                    "statut_compte",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("en_attente", "En attente"),
                            ("suspendu", "Suspendu"),
                            ("bloque", "Bloqué"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "photoProfil",
                    models.ImageField(blank=True, null=True, upload_to="profils/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruteurEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fonction", models.CharField(blank=True, max_length=150, null=True)),
                ("principal", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
                ("dateAssociation", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_recruteurs",
                        to="app_users.entreprise",
                    ),
                ),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_entreprises",
                        to="app_users.profil",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profil",
            name="entreprises",
            field=models.ManyToManyField(
                blank=True,
                related_name="recruteurs",
                through="app_users.RecruteurEntreprise",
                to="app_users.entreprise",
            ),
        ),
        migrations.AddConstraint(
            model_name="recruteurentreprise",
            constraint=models.UniqueConstraint(
                fields=("recruteur", "entreprise"), name="unique_recruteur_entreprise"
            ),
        ),
    ]
