# Generated by Django 5.2 on 2026-07-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="role",
            field=models.CharField(
                choices=[
                    ("candidat", "Candidat"),
                    ("recruteur", "Recruteur"),
                    ("admin", "Administrateur"),
                    ("freelance", "Freelance"),
                ],
                default="candidat",
                max_length=20,
            ),
        ),
    ]
