# Generated by Django 5.2 on 2026-08-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenceCandidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="debutant",
                        max_length=30,
                    ),
                ),
                ("anneesExperience", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competences",
                        to="app_users.profil",
                    ),
                ),
            ],
            options={
                "ordering": ["nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidat", "nom"), name="unique_competence_candidat"
                    )
                ],
            },
        ),
    ]
