# Generated by Django 5.2 on 2026-07-04 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=100)),
                ('chemin', models.CharField(max_length=255)),
                ('taille', models.IntegerField()),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.candidature')),
            ],
        ),
    ]
