# Generated by Django 5.2 on 2026-07-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_candidature_created_at_alter_document_chemin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='candidature',
        ),
    ]
