name: CI/CD - Frontend Angular vers Vercel

on:
  push:
    branches:
      - developpement
      - main
    paths:
      - "TalentHub-Front/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:

  # ==========================================================
  # TESTS ET BUILD ANGULAR
  # ==========================================================

  test-frontend:
    name:  Tests et Build Angular
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./TalentHub-Front

    steps:

      - name:  Récupérer le code
        uses: actions/checkout@v4

      - name:  Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ./TalentHub-Front/package-lock.json

      - name:  Installer les dépendances
        run: npm ci

      - name:  Exécuter les tests Angular
        run: npm test -- --watch=false

      - name:  Compiler Angular
        run: npm run build

  # ==========================================================
  # DEPLOIEMENT VERCEL
  # ==========================================================

  deploy:
    name:  Déploiement Frontend sur Vercel
    runs-on: ubuntu-latest

    needs:
      - test-frontend

    # Déploiement uniquement sur main
    if: github.ref == 'refs/heads/main'

    environment:
      name: production

    defaults:
      run:
        working-directory: ./TalentHub-Front

    steps:

      - name:  Récupérer le code
        uses: actions/checkout@v4

      - name:  Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name:  Installer Vercel CLI
        run: npm install --global vercel@latest

      - name:  Vérifier la configuration Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo " VERCEL_TOKEN est absent."
            exit 1
          fi

          echo " VERCEL_TOKEN est configuré."

      - name:  Récupérer la configuration Vercel
        run: |
          vercel pull \
            --yes \
            --environment=production \
            --token="$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name:  Construire le projet Vercel
        run: |
          vercel build \
            --prod \
            --token="$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Déployer sur Vercel
        run: |
          vercel deploy \
            --prebuilt \
            --prod \
            --token="$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
